### ISSUE TITLE
[FEATURE] Account

### ISSUE THREAD

**Issue by nueog2** [LikelionSnuggle/Snuggle-Backend#5]
## Description
주어진 ERD를 Snuggle 앱 내 회원가입 및 로그인, 로그아웃 기능 구현 

## Todo
진행상황
- [ ] 회원가입 앱 생성
- [ ] 유저 모델 작성
- [ ] 로그인
- [ ] 로그아웃 
- [ ] 회원가입 폼 및 views 작성 
- [ ] 비밀번호 유효성 부여 
- [ ] url 연결 

## ETA
10월 31일 이내 

## ETC
현재 실제로 돌리는 과정에서 keyerror가 발생해 해결하는 중입니다
코드는 짜놨으나 에러때문에 postman으로 돌아가는지 확인은 못했습니다
